### ISSUE TITLE
I couldn't get it to work with activate.exe

### ISSUE THREAD

**Issue by psyco752** [Luois45/claim-free-steam-packages#109]
Despite my attempts, every time I run activate.exe it doesn't work, I don't understand, I have asf and the bots configured well, but activate.exe doesn't work, the command screen appears for 1 second and it goes away by itself.

**Comment by Luois45** [comment]
Can you send the config.json file with all private information censored?

**Comment by Luois45** [comment]
Inactive for a month and archived due to this.
Will be reopened on further activity.
