### ISSUE TITLE
Stuck on 4337

### ISSUE THREAD

**Issue by dafunks** [Luois45/claim-free-steam-packages#110]
**Describe the bug**
Script is always opening on 4337 remaining free packages. For over 2 weeks now every time I open the script it is stuck on 4337. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open ASF
2. Open "Activate_packages.exe
3. Script starts and is on 0/4337
4. Repeat when I reopen next day

**Expected behaviour**
Continues to open free games counting down to 0

**Screenshots**
https://i.imgur.com/kiRHnV5.png
**Desktop (please complete the following information):**
 - Windows 11 21H2 22000.978
 - Brave (Chromium)
 - PowerShell 7.2.6

**Additional context**
This could have been happening much longer than 2 weeks. I just noticed then.

**Comment by Luois45** [comment]
Missing configuration file & inactive for a month and archived due to this.
Will be reopened on further activity.
