### ISSUE TITLE
Instructions if many packages are already claimed

### ISSUE THREAD

**Issue by woctezuma** [Luois45/claim-free-steam-packages#166]
I think there are a few issues with the instructions at [`docs/instructions-for-users-with-many-packages.md`](https://github.com/Luois45/claim-free-steam-packages/blob/main/docs/instructions-for-users-with-many-packages.md).

First, there is nothing displayed in the console.

Second, if I type `games`, then I see a list, but:
- it contains repetitions,
- it is truncated after 143 IDs:
```
"797921,797921,797922, [...] 681599,681599,781212…"
```

**Third, the list which I obtain is a list os `sub` IDs, while your `package_list.txt` is a list of `app` IDs.**

I believe it would make sense to use [`steamctl`](https://github.com/ValvePython/steamctl).

```txt
    apps                Get information about apps
    |- list               List owned or all apps
    \- licenses           Manage licenses
       \- list              List all licenses on account
```

or [`ASFEnhance`](https://github.com/chr233/ASFEnhance/blob/master/README.en.md).

```md
| Command                          | Shorthand | Access     | Description                                     |
| -------------------------------- | --------- | ---------- | ----------------------------------------------- |
| `FREELICENSES [Bots]`            | `FL`      | `Operator` | Get bot's all free sub licenses list            |
| `LICENSES [Bots]`                | `L`       | `Operator` | Get bot's all licenses list                     |
```

**Comment by woctezuma** [comment]
> First, there is nothing displayed in the console.

Not a big deal. ☑️  I can display the info with:
```js
games
```

> Second, if I type `games`, then I see a list, but:
> 
>     * it contains repetitions,
> 
>     * it is truncated after 143 IDs:

The repetitions are not there after I toggle OFF the browser extensions (SteamDB, Augmented Steam, ViolentMonkey).
I don't know which one was the culprit, but I suspect it is SteamDB. ☑️ 

The truncation is solved by double-clicking on the variable in the console. ☑️ 

> Third, the list which I obtain is a list os `sub` IDs, while your `package_list.txt` is a list of `app` IDs.

This issue remains! ❗

**Comment by woctezuma** [comment]
Only steamctl does the job:
- `steamctl apps list`: perfect
- `steamctl apps licenses list`: slow and slightly harder to parse, because there is more displayed data.

**Comment by woctezuma** [comment]
Another possibility is to download this JSON data **while authenticated**:
- https://store.steampowered.com/dynamicstore/userdata
- https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Dynamic-Store-User-Data

**Comment by Luois45** [comment]
Inactive for a month and archived due to this.
Will be reopened on further activity.

**Comment by woctezuma** [comment]
The issue is that the instructions at [`docs/instructions-for-users-with-many-packages.md`](https://github.com/Luois45/claim-free-steam-packages/blob/main/docs/instructions-for-users-with-many-packages.md) gives **a list of `sub` IDs, while your `package_list.txt` is a list of `app` IDs.**

To summarize the results of my investigation, the best solution would be to get the app IDs with `steamctl`.

Output of `steamctl apps list`: app IDs, including demos. 🥳 🎉 
```
[...]
1667640 Imagined Leviathans Demo
1667710 Gladihaters Demo
1667730 Forgotten Journey
1667770 Samurai Shampoo
1667810 Riding Seas Demo
[...]
```

**Comment by woctezuma** [comment]
Just to clarify all of these posts, I believe the instructions in `docs/` are wrong, and I suggest two workarounds.
