### ISSUE TITLE
Add documentation on how to run the Docker image

### ISSUE THREAD

**Issue by Luois45** [Luois45/claim-free-steam-packages#17]
**Is your feature request related to a problem? Please describe.**
There is no explanation on how to run the docker-compose.yml file or the Docker image.
Docker image: https://github.com/Luois45/claim-free-steam-packages/pkgs/container/claim-free-steam-packages
docker-compose.yml: https://github.com/Luois45/claim-free-steam-packages/blob/main/docker-compose.yml

**Describe the solution you'd like**
Add a documentation on how to run the image in Docker.

**Describe alternatives you've considered**
N/A

**Additional context**
As someone who does like to run applications inside Docker for easier management, I do think that such an explanation it would be really useful for people which aren't that familiar with docker

**Comment by Pilotkosinus** [comment]
There is a docker-compose file. Unfortunately the link to the image does not work because it is not public.

**Comment by Skaronator** [comment]
Would be cool to be able to configure everything from Environment Variables (even though it wouldn't be ideal for the password).

Additionally, the stdout log output doesn't seem to work correctly. The last output is always "Out of 17853 known free packages, 17853 are not already activated in your account. Beginning activation." and nothing after that will be printed. Would be great to have some feedback if it's actually doing something.


Other than that, thanks for providing a container image, thanks!
