### ISSUE TITLE
Workflows broke

### ISSUE THREAD

**Issue by ItsNiceCraft** [Luois45/claim-free-steam-packages#177]
**Describe the bug**
Github actions workflow to update the list of packages stopped running a while ago

Currently, the jobs can't find a self hosted runner to run on. Your self hosted runners are probably dead.
When trying to run on hosted runners (check [my fork](https://github.com/ItsNiceCraft/claim-free-steam-packages) for that), the workflow is [stuck on the "execute py script" step](https://github.com/ItsNiceCraft/claim-free-steam-packages/actions/runs/4336601049/jobs/7572007615).

**Comment by ItsNiceCraft** [comment]
Last passing run: https://github.com/Luois45/claim-free-steam-packages/actions/runs/4189264485

**Comment by woctezuma** [comment]
Right. The last update of the [`auto-update` branch](https://github.com/Luois45/claim-free-steam-packages/commits/auto-update) was two weekso ago, as the last passing run which you linked

**Comment by Luois45** [comment]
The problem is that my personal server went down but I'm currently working on the problem.

**Comment by ItsNiceCraft** [comment]
Why even use self hosted runners? Hosted runners are free for public repositories. Just change the
`runs-on: self-hosted` part to `runs-on: ubuntu-latest`

**Comment by Luois45** [comment]
I know but the workload is too much for hosted runners as well as caching wouldn't work on a hosted one.

**Comment by Luois45** [comment]
I got my runner in a working state again and it is just performing the first run again which _should_ be successful.
https://github.com/Luois45/claim-free-steam-packages/actions/runs/4507555150
Thanks for being so nice about it and sorry for the inconvenience caused by it.
