### ISSUE TITLE
Ability to filter packages to only include games/DLC

### ISSUE THREAD

**Issue by mgrimace** [Luois45/claim-free-steam-packages#38]
**Describe the solution you'd like**
Ideally, a way to select packages (e.g., to avoid game trailers and only pick games/DLC) if at all possible

**Additional context**
I apologize in advance if this already has that functionality, or if trailers/non-games are already filtered out. Thank you for your work.

**Comment by Luois45** [comment]
I don't think that I'll have enough time for that in the near future.

**Comment by mgrimace** [comment]
> I don't think that I'll have enough time for that in the near future.

Completely understandable! I don't know enough how this runs yet to contribute the solution myself, but I'll start taking a look (or if anyone else has suggestions let me know).

**Comment by Luois45** [comment]
Inactive for a month and archived due to this.
Will be reopened on further activity.
