### ISSUE TITLE
Super Slow? 

### ISSUE THREAD

**Issue by cwilliams5** [Luois45/claim-free-steam-packages#4]
**Describe the bug**
Look's like something is wrong with speed. 

**To Reproduce**
1. Run the program.
2. Items/Sec is very high.
3. Log is showing a bunch of odd repeats.

**Expected behavior**
Be able to add 50 licenses per hour as the Steam API allows. Perhaps even faster if ASF lets us know the product is already owned.

**Screenshots**
![image](https://user-images.githubusercontent.com/10100743/152607805-5035b205-5866-4a34-b7f3-cb99aead30b6.png)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
In the log I can see items repeating over and over. Even without repeating it would be slow, but this is slowing it way further.

Also ASF !addlicense accepts a comma seperated list, wouldn't that be faster to do 50 at a time that way? Although maybe you don't get back enough in the response to know what to log/retry, I don't know.

Logging data:
`12:47:14,989 urbanGUI DEBUG Found config file
12:47:14,989 asyncio DEBUG Using proactor: IocpProactor
12:47:15,550 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): raw.githubusercontent.com:443
12:47:15,892 urllib3.connectionpool DEBUG https://raw.githubusercontent.com:443 "GET /Luois45/claim-free-steam-packages/update-package_list/package_list.txt HTTP/1.1" 200 42184
12:47:15,921 urbanGUI DEBUG 
Package found in activated_packages
12:47:15,922 urbanGUI DEBUG 
Package not found in activated_packages
12:47:16,106 urbanGUI INFO 
<IPC> ID: app/1446570 | Status: OK | Items: app/1446570

12:48:46,109 urbanGUI DEBUG 
Package not found in activated_packages
12:48:46,255 urbanGUI INFO 
<IPC> ID: app/1446670 | Status: OK | Items: app/1446670

12:50:16,269 urbanGUI DEBUG 
Package not found in activated_packages
12:50:16,451 urbanGUI INFO 
<IPC> ID: app/1446720 | Status: OK | Items: app/1446720

12:51:46,459 urbanGUI DEBUG 
Package not found in activated_packages
12:51:46,656 urbanGUI INFO 
<IPC> ID: app/1446740 | Status: OK | Items: app/1446740

12:53:16,664 urbanGUI DEBUG 
Package not found in activated_packages
12:53:16,879 urbanGUI INFO 
<IPC> ID: app/1445970 | Status: OK | Items: app/1445970

12:54:46,889 urbanGUI DEBUG 
Package not found in activated_packages
12:54:47,119 urbanGUI INFO 
<IPC> ID: app/1446020 | Status: OK | Items: app/1446020

12:56:17,133 urbanGUI DEBUG 
Package not found in activated_packages
12:56:17,315 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

12:57:47,524 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

12:59:17,719 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:00:47,920 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:02:18,130 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:03:48,333 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:05:18,537 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:06:48,734 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:08:18,936 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:09:49,145 urbanGUI INFO 
<IPC> ID: app/1446120 | Status: OK

13:12:49,161 urbanGUI DEBUG 
Package not found in activated_packages
13:12:49,392 urbanGUI INFO 
<IPC> ID: app/1446230 | Status: OK | Items: app/1446230

13:14:19,402 urbanGUI DEBUG 
Package not found in activated_packages
13:14:19,598 urbanGUI INFO 
<IPC> ID: app/1445330 | Status: OK | Items: app/1445330

13:15:49,613 urbanGUI DEBUG 
Package not found in activated_packages
13:15:49,800 urbanGUI INFO 
<IPC> ID: app/1445510 | Status: OK | Items: app/1445510

13:17:19,817 urbanGUI DEBUG 
Package not found in activated_packages
13:17:20,18 urbanGUI INFO 
<IPC> ID: app/1445610 | Status: OK | Items: app/1445610

13:18:50,25 urbanGUI DEBUG 
Package not found in activated_packages
13:18:50,253 urbanGUI INFO 
<IPC> ID: app/1445640 | Status: OK | Items: app/1445640

13:20:20,258 urbanGUI DEBUG 
Package not found in activated_packages
13:20:20,457 urbanGUI INFO 
<IPC> ID: app/1445700 | Status: OK | Items: app/1445700

13:21:50,467 urbanGUI DEBUG 
Package not found in activated_packages
13:21:50,665 urbanGUI INFO 
<IPC> ID: app/1445710 | Status: OK | Items: app/1445710

13:23:20,679 urbanGUI DEBUG 
Package not found in activated_packages
13:23:20,868 urbanGUI INFO 
<IPC> ID: app/1444970 | Status: OK | Items: app/1444970

13:24:50,871 urbanGUI DEBUG 
Package not found in activated_packages
13:24:51,61 urbanGUI INFO 
<IPC> ID: app/1445040 | Status: OK | Items: app/1445040

13:26:21,68 urbanGUI DEBUG 
Package not found in activated_packages
13:26:21,420 urbanGUI INFO 
<IPC> ID: app/1445170 | Status: OK

13:27:51,634 urbanGUI INFO 
<IPC> ID: app/1445170 | Status: OK

13:29:21,824 urbanGUI INFO 
<IPC> ID: app/1445170 | Status: OK

13:30:52,29 urbanGUI INFO 
<IPC> ID: app/1445170 | Status: OK

13:32:22,288 urbanGUI INFO 
<IPC> ID: app/1445170 | Status: OK

`

**Comment by Luois45** [comment]
I've had a look into it, and it seems like it is happening because of a bug in the code which does reduce the possible speed by quite a lot.
I will create a pr fixing the bug later today.

**Comment by cwilliams5** [comment]
Yep, can confirm I'm getting 90.2s/it now, so its matching the sleep. Ty for fixing. Don't forget to burn a new .exe for those who need it. 

Oh and threw an idea in #5 that would also help with speed.

**Comment by Luois45** [comment]
Thanks for the reminder.
I will build a new exe file in the next few days.
Had already a look at the idea in #5, but will answer there.
